language: node_js
node_js:
  - "0.10.40"
addons:
  sauce_connect: true
before_script:
  - npm install && npm start & # Run in the background
script:
   - npm test && npm run e2e-remote
   - pkill node # Kill the app
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#jsbin"
    on_success: change
    on_failure: always
