language: node_js
node_js:
  - "0.10.40"
addons:
  sauce_connect: true
before_script:
  - npm install
  - test "$TRAVIS_PULL_REQUEST" = "false" && npm start&
script:
  - npm test
  - test "$TRAVIS_PULL_REQUEST" = "false" && npm run e2e-remote
  - test "$TRAVIS_PULL_REQUEST" = "false" && pkill node || exit 0

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#jsbin"
    on_success: change
    on_failure: always
