language: node_js
node_js:
  - "6"
addons:
  sauce_connect: true
before_script:
  - test "$TRAVIS_PULL_REQUEST" = "false" && yarn start&
script:
  - yarn test
  - test "$TRAVIS_PULL_REQUEST" = "false" && yarn run e2e-remote
  - test "$TRAVIS_PULL_REQUEST" = "false" && pkill node || exit 0

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#jsbin"
    on_success: change
    on_failure: always
