language: node_js
node_js:
  - "0.10.40"
before_script:
  - npm install
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#jsbin"
    on_success: change
    on_failure: always
