module.exports = {
  'General JavaScript  test' : function (client) {
    var data = client.globals;
    client
      .url(client.launch_url)
      .waitForElementVisible('#panel-javascript')
      .click('#panel-javascript')
      .waitForElementVisible('.javascript .CodeMirror')
      client.execute(function (text){
        return $('.javascript .CodeMirror')[0].CodeMirror.setValue(text);
      }, ["document.body.innerHTML = 'Hello'"])
      client.click('a[href="#javascriptprocessors"]')
      .click('a[id="processor-javascript"]').pause(data.defaultTime)
      .frame(2)
      .assert.containsText('body', 'Hello')
      .click('a[href="#javascriptprocessors"]')
      .click('a[id="processor-babel"]')
      .pause(data.defaultTime)
      .frame(2)
      .assert.containsText('body', 'Hello')
      .click('a[href="#javascriptprocessors"]')
      .click('a[id="processor-jsx"]')
      .pause(data.defaultTime)
      .frame(2)
      .assert.containsText('body', 'Hello')
      .click('a[href="#javascriptprocessors"]')
      .click('a[id="processor-coffeescript"]')
      .pause(data.defaultTime)
      .frame(2)
      .assert.containsText('body', 'Hello')
      .click('a[href="#javascriptprocessors"]')
      .click('a[id="processor-traceur"]')
      .pause(data.defaultTime)
      .frame(2)
      .assert.containsText('body', 'Hello')
      .click('a[href="#javascriptprocessors"]')
      .click('a[id="processor-typescript"]')
      .pause(data.defaultTime)
      .frame(2)
      .assert.containsText('body', 'Hello')
      .click('a[href="#javascriptprocessors"]')
      .click('a[id="processor-processing"]')
      .pause(data.defaultTime)
      .frame(2)
      .assert.containsText('body', 'Hello')
      .click('a[href="#javascriptprocessors"]')
      .click('a[id="processor-livescript"]')
      .pause(data.defaultTime)
      .frame(2)
      .assert.containsText('body', 'Hello')
      .click('a[href="#javascriptprocessors"]')
      .click('a[id="processor-convert"]')
      .pause(data.defaultTime)
      .frame(2)
      .assert.containsText('body', 'Hello')
      .assert.urlMatch(/\/\w+\/edit\?html,js,output$/)
      .end();
  }
};
